/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.cityOfficialsWorkArea;

import businesslogic.CityNetwork;
import businesslogic.EcoSystem;
import businesslogic.User;
import businesslogic.organization.OrgManager;
import businesslogic.organization.Organization;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anshitaverma
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewOrganizationJPanel
     */
        private JPanel userProcessContainer;
        private User userLogged;
        private EcoSystem ecoSystem;
        private CityNetwork cityNetwork;
        
    public ManageOrganizationJPanel(JPanel jpanel, User userLogged, EcoSystem ecoSystem, CityNetwork cityNetwork) {
        this.ecoSystem=ecoSystem;
        this.userLogged=userLogged;
        this.userProcessContainer=jpanel;
        this.cityNetwork=cityNetwork;
        initComponents();
        populateData();
        
        lblheadercityName.setText(cityNetwork.getCityName().name());       
    }
    
    public void populateData(){
        DefaultTableModel model = (DefaultTableModel) manageOrgtbl.getModel();
        model.setRowCount(0);
        int count=0;
        for(Organization org:cityNetwork.getOrganizationDirectory().getOrganizations()){
            count++;
            Object[] row = new Object[7];
            row[0]=count;
            row[1]=org;
            row[2]=org.getOrganizationType();
            row[3]=org.getAddress();
            row[4]=org.getPhoneNo();
            row[5]=org.getEmail();
            row[6]=org.getCreatedBy();
            
            model.addRow(row);
        }
        DefaultTableModel managersModel = (DefaultTableModel) managerOrgtbl.getModel();
        managersModel.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageOrgtbl = new javax.swing.JTable();
        addOrgbtn = new javax.swing.JButton();
        updateOrgbtn = new javax.swing.JButton();
        deleteOrgbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        managerOrgtbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        addManagerbtn = new javax.swing.JButton();
        updateManagerbtn = new javax.swing.JButton();
        deleteManagerbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        managerOrgbtn = new javax.swing.JButton();
        lblheadercityName = new javax.swing.JLabel();
        lblheadercityTag = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Organizations ");
        add(jLabel1);
        jLabel1.setBounds(310, 18, 301, 29);

        manageOrgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Organization Name", "Organization Type", "Address", "Mobile Number", "Email Id", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manageOrgtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageOrgtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manageOrgtbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(31, 62, 903, 169);

        addOrgbtn.setText("Add");
        addOrgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgbtnActionPerformed(evt);
            }
        });
        add(addOrgbtn);
        addOrgbtn.setBounds(879, 249, 55, 25);

        updateOrgbtn.setText("Update");
        updateOrgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrgbtnActionPerformed(evt);
            }
        });
        add(updateOrgbtn);
        updateOrgbtn.setBounds(707, 249, 73, 25);

        deleteOrgbtn.setText("Delete");
        deleteOrgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgbtnActionPerformed(evt);
            }
        });
        add(deleteOrgbtn);
        deleteOrgbtn.setBounds(792, 249, 69, 25);

        managerOrgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Manager Name", "Mobile Number", "Email Id", "Address", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(managerOrgtbl);

        add(jScrollPane2);
        jScrollPane2.setBounds(31, 359, 903, 180);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Organization Manager");
        add(jLabel2);
        jLabel2.setBounds(292, 292, 397, 41);

        addManagerbtn.setText("Add");
        addManagerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManagerbtnActionPerformed(evt);
            }
        });
        add(addManagerbtn);
        addManagerbtn.setBounds(879, 557, 55, 25);

        updateManagerbtn.setText("Update");
        updateManagerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateManagerbtnActionPerformed(evt);
            }
        });
        add(updateManagerbtn);
        updateManagerbtn.setBounds(707, 557, 73, 25);

        deleteManagerbtn.setText("Delete");
        deleteManagerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteManagerbtnActionPerformed(evt);
            }
        });
        add(deleteManagerbtn);
        deleteManagerbtn.setBounds(798, 557, 69, 25);

        backbtn.setText("< < Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn);
        backbtn.setBounds(31, 24, 85, 25);

        managerOrgbtn.setText("Manage Organization Manager");
        managerOrgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerOrgbtnActionPerformed(evt);
            }
        });
        add(managerOrgbtn);
        managerOrgbtn.setBounds(493, 249, 207, 25);
        add(lblheadercityName);
        lblheadercityName.setBounds(800, 20, 130, 30);

        lblheadercityTag.setText("City:");
        add(lblheadercityTag);
        lblheadercityTag.setBounds(750, 20, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addManagerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManagerbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Restaurant to add Managers");
            return;
        } else {
            DefaultTableModel organizationsModel = (DefaultTableModel) manageOrgtbl.getModel();
            Organization selectedOrganization = (Organization) organizationsModel.getValueAt(selectedRow, 1);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("SysAdminCreateManagerPanel", new CreateOrgManagerJPanel(userProcessContainer, ecoSystem, cityNetwork, selectedOrganization, userLogged));
            cardLayout.next(userProcessContainer);

        }

    }//GEN-LAST:event_addManagerbtnActionPerformed

    private void deleteOrgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization org = (Organization) manageOrgtbl.getValueAt(selectedRow, 1);
            
            cityNetwork.getOrganizationDirectory().getOrganizations().remove(org);
           
            JOptionPane.showMessageDialog(null, "Organization deleted Successfully! ");
            populateData();
        }
    }//GEN-LAST:event_deleteOrgbtnActionPerformed

    private void managerOrgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerOrgbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization org = (Organization) manageOrgtbl.getValueAt(selectedRow, 1);
            DefaultTableModel managersModel = (DefaultTableModel) managerOrgtbl.getModel();
            managersModel.setRowCount(0);
            int employeeCount=0;
            for(OrgManager orgManager:org.getOrgManagerDirectory().getOrgManagers()) {
                employeeCount++;
                Object[] row = new Object[7];
                row[0] = employeeCount;
                row[1] = orgManager;
                row[2] = orgManager.getPhoneNo();
                row[3] = orgManager.getEmail();
                row[4] = orgManager.getAddress();
                row[5] = orgManager.getUserName();
                row[6] = orgManager.getPassword();
                managersModel.addRow(row);
            }
        }
    }//GEN-LAST:event_managerOrgbtnActionPerformed

    private void deleteManagerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteManagerbtnActionPerformed
        // TODO add your handling code here:
        int selectedManager = managerOrgtbl.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to delete");
            return;
        }
        DefaultTableModel managerModel = (DefaultTableModel) managerOrgtbl.getModel();
        OrgManager orgManager = (OrgManager) managerOrgtbl.getValueAt(selectedManager, 1);
        
        int selectedRow = manageOrgtbl.getSelectedRow();
        DefaultTableModel orgManagerModel = (DefaultTableModel) manageOrgtbl.getModel();
        Organization org = (Organization) orgManagerModel.getValueAt(selectedRow, 1);
    
        org.getOrgManagerDirectory().getOrgManagers().remove(orgManager);
        JOptionPane.showMessageDialog(this, "Successfully deleted Manager");
      
        populateData();
    
        
    }//GEN-LAST:event_deleteManagerbtnActionPerformed

    private void updateManagerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateManagerbtnActionPerformed
        // TODO add your handling code here:
        int selectedManager = managerOrgtbl.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to Update");
            return;
        }
        DefaultTableModel organizationManagerModel = (DefaultTableModel) managerOrgtbl.getModel();
        OrgManager orgManager = (OrgManager) organizationManagerModel.getValueAt(selectedManager, 1);

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("UpdateOrganizationManagerPanel", new UpdateOrgManagerJPanel(userProcessContainer, ecoSystem, cityNetwork, orgManager, userLogged));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_updateManagerbtnActionPerformed

    private void updateOrgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrgbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization selectedOrganization = (Organization) manageOrgtbl.getValueAt(selectedRow, 1);
            UpdateOrganizationJPanel updateOrganizationJPanel = new UpdateOrganizationJPanel(userProcessContainer, ecoSystem, cityNetwork, selectedOrganization, userLogged);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("UpdateOrganizationPanel", updateOrganizationJPanel);
    
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateOrgbtnActionPerformed

    private void addOrgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgbtnActionPerformed
        // TODO add your handling code here:
        CreateOrganizationJPanel panel = new CreateOrganizationJPanel(userProcessContainer, ecoSystem, userLogged,cityNetwork );
        //          userProcessContainer.remove(this);
        userProcessContainer.add("CreateNewOrganizationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addOrgbtnActionPerformed

    private void manageOrgtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrgtblMouseClicked
        managerOrgbtnActionPerformed(null);
    }//GEN-LAST:event_manageOrgtblMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addManagerbtn;
    private javax.swing.JButton addOrgbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteManagerbtn;
    private javax.swing.JButton deleteOrgbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblheadercityName;
    private javax.swing.JLabel lblheadercityTag;
    private javax.swing.JTable manageOrgtbl;
    private javax.swing.JButton managerOrgbtn;
    private javax.swing.JTable managerOrgtbl;
    private javax.swing.JButton updateManagerbtn;
    private javax.swing.JButton updateOrgbtn;
    // End of variables declaration//GEN-END:variables
}
