/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemAdminsWorkArea;

import businesslogic.CityNetwork;
import businesslogic.EcoSystem;
import businesslogic.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class SysAdminManageCityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminManageCityJPanel
     */
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userLogged;
    
    public SysAdminManageCityJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork,
            User userLogged) {
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        initComponents();
        
        lblcity.setText(cityNetwork.getCityName().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        headerjLabel = new javax.swing.JLabel();
        manageOrganizationsjButton = new javax.swing.JButton();
        manageDonorsjButton = new javax.swing.JButton();
        manageCityOfficialsjButton = new javax.swing.JButton();
        lblcity = new javax.swing.JLabel();

        backjButton.setText("< < Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        headerjLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel.setText("Manage Data in the City ");

        manageOrganizationsjButton.setText("Manage Organizations >");
        manageOrganizationsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationsjButtonActionPerformed(evt);
            }
        });

        manageDonorsjButton.setText("Manage Donors >");
        manageDonorsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDonorsjButtonActionPerformed(evt);
            }
        });

        manageCityOfficialsjButton.setText("Manage CityOfficials >");
        manageCityOfficialsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCityOfficialsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backjButton)
                        .addGap(74, 74, 74)
                        .addComponent(headerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(manageDonorsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageOrganizationsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(manageCityOfficialsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(403, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {manageCityOfficialsjButton, manageDonorsjButton, manageOrganizationsjButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(manageOrganizationsjButton)
                .addGap(18, 18, 18)
                .addComponent(manageDonorsjButton)
                .addGap(18, 18, 18)
                .addComponent(manageCityOfficialsjButton)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessJpanel.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        Component[] components = userProcessJpanel.getComponents();
        SysAdminHomeJPanel sysAdminHomeJPanel = (SysAdminHomeJPanel) components[components.length-1];
        sysAdminHomeJPanel.populateSysAdmins();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void manageOrganizationsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationsjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminOrganizationManagePanel", new ManageOrganizationsJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageOrganizationsjButtonActionPerformed

    private void manageDonorsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDonorsjButtonActionPerformed
        // TODO add your handling code here:

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminDonorManagePanel", new ManageDonorsJpanel(userProcessJpanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageDonorsjButtonActionPerformed

    private void manageCityOfficialsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCityOfficialsjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminCityOfficialManagePanel", new ManageCityOfficialsJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageCityOfficialsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel lblcity;
    private javax.swing.JButton manageCityOfficialsjButton;
    private javax.swing.JButton manageDonorsjButton;
    private javax.swing.JButton manageOrganizationsjButton;
    // End of variables declaration//GEN-END:variables
}
